// <auto-generated />
using CoreMvc.Models.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CoreMvc.Migrations
{
    [DbContext(typeof(CoreMvcDbContext))]
    [Migration("20180122161940_CriacaoInicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("CoreMvc.Models.Entities.Meta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.Property<float>("Pontos");

                    b.HasKey("Id");

                    b.ToTable("meta");
                });

            modelBuilder.Entity("CoreMvc.Models.Entities.MetaRealizada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("MetaId");

                    b.Property<float>("QuantidadeRealizada");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("metaRealizada");
                });

            modelBuilder.Entity("CoreMvc.Models.Entities.MetaRealizada", b =>
                {
                    b.HasOne("CoreMvc.Models.Entities.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId");
                });
#pragma warning restore 612, 618
        }
    }
}
